import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { ModeToggle } from "@/components/mode-toggle"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Void Pixel",
    description: "Generated by create next app",
};

export default function Home() {
    return(
        <div>
            Hello World
        </div>
    );
}
